### ISSUE TITLE
Provisionando uma aplicação na Digital Ocean utilizando Droplets e Docker Stack

### ISSUE THREAD

**Issue by RegisBarros** [JessicaNathany/dev-solutions#2]
# Provisionando uma aplicação na Digital Ocean utilizando Droplets e Docker

Para quem nunca usou Digital Ocean, os Droplets são maquinas virtuais, assim como o EC2 na AWS, sendo um alternativa de baixo custo para quem quer explorar uma outra alternativa de cloud solution.
As aplicações que iriam ser configuradas nesse ambiente eram duas aplicações frontends escritas em ReactJs (SPAs - Single Page Application), uma aplicação frontend escrita em NextJs sendo um SSR (Server Side Render) e uma rest api escrita utilizando AdonisJs um framework javascript baseado no Laravel do PHP.

Então decidimos provisionar essas aplicações utilizando Docker Compose, o que facilitaria a configuração e a gestão dessas aplicações, e para isso vimos que a melhor maneira para rodar uma aplicação com Docker num ambiente produtivo era utilizando Docker Stack, também conhecido como Docker Swarm ou Docker Services.

Abaixo segue os passos que fizemos para configurar as aplicações:

1. Criação do arquivo docker-compose:
``` yaml
version: "3.4"

services:
  app:
    image: registry.gitlab.com/7belts/frontend:latest
    networks:
      - 7beltsNET
    ports:
      - "5300:80"
    depends_on:
      - api
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

  api:
    image: registry.gitlab.com/7belts/backend:latest
    networks:
      - 7beltsNET
    ports:
      - "5400:3333"
    environment:
      ENV_PATH: .env.production
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
  
  ssr-front:
    image: registry.gitlab.com/7belts/ssr-front:latest
    networks:
      - 7beltsNET
    ports:
      - "5500:3000"    
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

  proxy_server:
    image: registry.gitlab.com/7belts/infrastructure:latest
    networks:
      - 7beltsNET
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - api
      - ssr-front
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  7beltsNET:
    driver: overlay
```

2. Criar uma conta na Digital Ocean e gerar um token de acesso:
![19B73BFC-BC3E-4115-8FAC-C8950CD305AE](https://github.com/JessicaNathany/dev-solutions/assets/13111721/f40b3c5b-10c6-438d-9af5-8eb34e7402bd)

3. Adicione o access token nas suas variáveis de ambiente:
``` bash
export DIGITAL_OCEAN_ACCESS_TOKEN=[your_digital_ocean_token]
```

4. Criando um droplet na Digital Ocean utilizando *docker machine*:
``` bash
docker-machine create --driver digitalocean --digitalocean-image ubuntu-20-04-x64 --digitalocean-access-token $DOTOKEN prod-swarm-master
```

5. Inicializando o cluster:
```bash
docker-machine ssh prod-swarm-master

docker swarm init --advertise-addr {{node_ip_address}}
```

*Importante*: /*node_ip_address*/ is the IP address of the node. You may get it from the output of docker-machine ls or from your DigitalOcean dashboard.

6. Criando um registry privado no cluster:
```bash
docker service create --name registry --publish published=5000,target=5000 registry:2
```

7. Subindo seu docker compose para o registry:
```bash
docker-compose build .
docker-compose push
```

8. Realizando o deploy da aplicação:
```bash
docker stack deploy --compose-file docker-compose.yml --with-registry-auth 7belts-app
```

9. Verificando se a aplicação está rodando:
```bash
docker stack services 7belts-app
```

Pronto, nesse momento as aplicações que foram configuradas no docker-compose já estão rodando no nosso Droplet da Digital Ocean, e veja que nesse caso não precisei acessar a maquina virtual remotamente, instalar e configurar o docker. O docker machine realiza toda essa configuração automaticamente e isso facilita muito nossa vida.

E como estamos usando o Docker Swarm que é um orchestrator, conseguimos de uma maneira muito simples escalar nossa aplicação.

Nesse exemplo estou escalando o backend para rodar com 4 instâncias:
``` bash
docker service scale api=4
```

Também é possível derrubar o ambiente através do seguinte comando:
```bash
docker stack rm 7belts-app
```

Caso queira remover meu cluster:
```bash
docker-machine rm prod-swarm-master
```

E caso você precise atualizar alguma configuração do arquivo docker-compose:
```bash
docker-machine scp -r ./docker-compose.yml prod-swarm-master:/root/docker-compose.yml
```

E para finalizar, no projeto estamos utilizando uma pipeline (CI/CD) no Gitlab, e a cada build realizado, era executado o seguinte comando para atualizar as aplicações no Droplet:
```bash
docker service update --image registry.gitlab.com/7belts/frontend:latest --with-registry-auth 7belts-app_app
docker service update --image registry.gitlab.com/7belts/backend:latest --with-registry-auth 7belts-app_api
```

Referências:
[Deploy to Swarm | Docker Documentation](https://docs.docker.com/get-started/swarm-deploy)
[How To Provision and Manage Remote Docker Hosts with Docker Machine on Ubuntu 18.04  | DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-provision-and-manage-remote-docker-hosts-with-docker-machine-on-ubuntu-18-04)
[How to Create a Cluster of Docker Containers with Docker Swarm and DigitalOcean on CentOS 7  | DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-create-a-cluster-of-docker-containers-with-docker-swarm-and-digitalocean-on-centos-7)
[Running Spark with Docker Swarm on DigitalOcean | TestDriven.io](https://testdriven.io/blog/running-spark-with-docker-swarm-on-digitalocean/)
